name: Vida
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # For icon
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  ionicons: ^0.2.2
  animations: ^2.0.1
  flutter_launcher_icons: ^0.13.1

  # For audio
  just_audio: ^0.9.32
  on_audio_query: ^2.9.0
  permission_handler: ^10.2.0
  pull_to_refresh: ^2.0.0
  async: ^2.10.0
  downloads_path_provider_28: ^0.1.2
  dart_tags: ^0.4.0
  flutter_media_metadata: ^1.0.0+1

  # For networking
  dio: ^5.3.3
  http: ^0.13.5

  # For bloc
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  json_serializable: ^6.6.1
  json_annotation: ^4.8.1
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # For bloc
  build_runner: ^2.4.6
  freezed: ^2.4.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logo/play_store_512.png"
  adaptive_icon_foreground: "assets/image/logo/play_store_512.png"
  adaptive_icon_background: "assets/image/logo/play_store_512.png"

flutter:
  uses-material-design: true

  assets:
    - assets/image/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/font/Comfortaa-Bold.ttf
        - asset: assets/font/Comfortaa-Light.ttf
        - asset: assets/font/Comfortaa-Medium.ttf
        - asset: assets/font/Comfortaa-Regular.ttf
        - asset: assets/font/Comfortaa-Semibold.ttf
