name: Vida
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  just_audio: ^0.9.32
  on_audio_query: ^2.7.0
  permission_handler: ^10.2.0
  intl: ^0.17.0
  animations: ^2.0.1

  ionicons: ^0.2.2
  http: ^0.13.5
  pull_to_refresh: ^2.0.0
  

  async: ^2.10.0


  flutter_file_downloader: ^1.1.2
 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
  
  fonts:
    - family: Comfortaa
      fonts:
        
        - asset: assets/font/Comfortaa-Bold.ttf
        - asset: assets/font/Comfortaa-Light.ttf
        - asset: assets/font/Comfortaa-Medium.ttf
        - asset: assets/font/Comfortaa-Regular.ttf
        - asset: assets/font/Comfortaa-Semibold.ttf
 
