/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adminpage;

import controller.HomePageController;

public class App {

    public static void main(String[] args) {
        HomePageController homePageController = new HomePageController();
        homePageController.showGUI(true);

    }
}
