/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package adminpage;

import controller.HomePageController;

public class App {
    public static HomePageController homePageController = new HomePageController();

    public static void main(String[] args) {
        homePageController.showGUI();
    }
}
